services:

  tokosepatu:
    container_name: TOKO_SEPATU
    build: .
    volumes:
      - ./breeze:/var/www/html
    ports:
      - 9000:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: breeze
    ports:
    - 3307:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9002:80
    environment:
      - PMA_ARBITRARY=1